CPPFLAGS = -std=c++17 -Wall -Wextra -Werror -Wfatal-errors -Wno-sign-compare -Wnon-virtual-dtor -g

# type "make" to run these commands

all: 
	g++ -c $(CPPFLAGS) Candy.cpp
	g++ -c $(CPPFLAGS) Database.cpp
	g++ -c $(CPPFLAGS) Menu.cpp
	g++ -c $(CPPFLAGS) Main.cpp
	g++ -o a5 Candy.o Database.o Menu.o Main.o